#!/bin/sh
# Deprecated alias of ./mhw (Issue #68): the command was renamed. Same arguments, same behaviour, one
# notice on stderr. Removed in the next major release.
dir=$(cd "$(dirname "$0")" && pwd)
# shellcheck disable=SC2016  # the backticks are literal text
echo '`workstation` is renamed `mhw`; the alias will be removed in the next major' >&2
exec /bin/sh "$dir/mhw" "$@"
