#!/usr/bin/python3
# Clipboard guard (ADR-0011): watch the macOS pasteboard and catch employer/client terms, credentials
# and personal data in what is copied, before it is pasted into any prompt.
#
#   clipboard_guard.py watch [--config FILE]   the background watcher (run by the LaunchAgent)
#   clipboard_guard.py add-term [--config FILE] add one term to the hashed list, typed at the terminal
#   clipboard_guard.py check-config [--config FILE]  print the effective non-secret settings
#
# Properties this file must keep, each with a test in clipboard_guard_test.py:
#   - it writes NOTHING except the clipboard (when told to) and the term list (add-term only):
#     no log, no history, no cache, no record of what matched (ADR-0005);
#   - a notice names categories and the mitigation, never the content or the matched term;
#   - an item marked concealed, transient or auto-generated (nspasteboard.org) is never read past its
#     type list, so a password-manager copy never reaches the detector;
#   - the term list holds salted hashes of normalised terms, never plaintext, and add-term reads the
#     term from the terminal with echo off: never from argv, the environment or a pipe.
#
# Standard library only. Runs on the Command Line Tools python3 (3.9) and later.
import hashlib
import hmac
import os
import re
import secrets
import subprocess
import sys
import time
import unicodedata

PROJECT = "personal-multi-harness-workstation-configuration"
SKIP_TYPES = (
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
)
# Qt applications (KeePassXC, read in its source 2026-10-01) declare the marker as the MIME name
# "application/x-nspasteboard-concealed-type". Whether Qt turns that into the exact UTI above or into a
# Qt-generated type name was NOT established, so any type whose name carries the marker is skipped too.
# Erring toward skipping costs one unchecked item; erring the other way can redact a copied password.
SKIP_SUBSTRINGS = ("nspasteboard-concealed", "nspasteboard-transient", "nspasteboard-autogenerated")
TEXT_TYPE = "public.utf8-plain-text"
MAX_TERM_TOKENS = 6
MIN_TERM_CHARS = 3
TERMS_HEADER = "# %s clipboard terms v1: HMAC-SHA256(salt, normalised term), one per line; never plaintext\n" % PROJECT

# --------------------------------------------------------------------------------------------- config

DEFAULTS = {
    "mode": "offer",            # offer (ask: clean / clear / keep) | sanitise (replace, then notify)
    "poll_seconds": "1",
    "max_bytes": "1000000",
    "salt_store": "",           # keychain | file; empty means keychain on macOS, file elsewhere
    "keychain_service": PROJECT + ".clipboard-salt",
    "terms_file": "",           # empty means <local overlay>/clipboard-terms
    "salt_file": "",            # empty means <local overlay>/clipboard-salt (salt_store=file only)
    "osascript": "/usr/bin/osascript",
    "dialog_seconds": "120",
    "title": "Workstation firewall",
    "button_keep": "Keep",
    "button_clear": "Clear",
    "button_clean": "Clean",
    "notice_offer": "Clipboard check (ADR-0011): {categories} in the copied item. Nothing changed yet: "
                    "Clean replaces it with a redacted copy, Clear empties the clipboard, Keep leaves it.",
    "notice_cleaned": "Clipboard check (ADR-0011): {categories} in the copied item. "
                      "Mitigation: replaced with a redacted plain-text copy.",
    "notice_cleared": "Clipboard check (ADR-0011): {categories} in the copied item. Mitigation: clipboard cleared.",
    "notice_changed": "Clipboard check (ADR-0011): {categories} in a copied item, but the clipboard changed "
                      "before the mitigation ran. Mitigation: none applied.",
    "notice_too_large": "Clipboard check (ADR-0011): a copied item over {max} bytes was NOT checked.",
    "notice_error": "Clipboard check (ADR-0011): watcher error ({error}); the copied item was NOT checked.",
    "notice_no_salt": "Clipboard check (ADR-0011): the term list exists but its salt was not found, "
                      "so employer/client term matching is OFF.",
}
MODES = ("offer", "sanitise")


def data_dir():
    base = os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share")
    return os.path.join(base, PROJECT)


def local_overlay_dir():
    """Untracked, user-only, outside every repository: where the term list and a file salt live."""
    return os.path.join(data_dir(), "local-overlay")


def load_config(path):
    """key=value per line, '#' comments, last value wins; an invalid value falls back to its default."""
    conf = dict(DEFAULTS)
    if path and os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.rstrip("\r\n")
                if not line.strip() or line.lstrip().startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                if key in DEFAULTS:
                    conf[key] = value.strip() if not key.startswith("notice_") else value
    if conf["mode"] not in MODES:
        conf["mode"] = DEFAULTS["mode"]
    for key in ("poll_seconds", "max_bytes", "dialog_seconds"):
        if not conf[key].isdigit() or int(conf[key]) < 1:
            conf[key] = DEFAULTS[key]
    if conf["salt_store"] not in ("keychain", "file"):
        conf["salt_store"] = "keychain" if sys.platform == "darwin" else "file"
    if not conf["terms_file"]:
        conf["terms_file"] = os.path.join(local_overlay_dir(), "clipboard-terms")
    if not conf["salt_file"]:
        conf["salt_file"] = os.path.join(local_overlay_dir(), "clipboard-salt")
    return conf

# ---------------------------------------------------------------------------------- normalisation


def _is_word_char(ch):
    return unicodedata.category(ch)[0] in "LNM"


def tokens(text):
    """[(start, end, normalised)] for each word in text. A word is a run of letters, digits and
    combining marks; everything else separates. Normalised: accents dropped, case folded."""
    out = []
    i, n = 0, len(text)
    while i < n:
        if not _is_word_char(text[i]) or unicodedata.category(text[i])[0] == "M":
            i += 1
            continue
        j = i + 1
        while j < n and _is_word_char(text[j]):
            j += 1
        norm = _normalise_word(text[i:j])
        if norm:
            out.append((i, j, norm))
        i = j
    return out


def _normalise_word(word):
    decomposed = unicodedata.normalize("NFKD", word).casefold()
    return "".join(c for c in decomposed if unicodedata.category(c)[0] in "LN")


def term_forms(term):
    """The normalised forms stored for one term: words joined by a space and, for a multi-word term,
    also run together (so 'Acme Corp' also matches 'AcmeCorp' and 'acme_corp')."""
    words = [t[2] for t in tokens(term)]
    if not words:
        return []
    forms = [" ".join(words)]
    if len(words) > 1:
        forms.append("".join(words))
    return forms


def term_hash(salt, form):
    return hmac.new(bytes.fromhex(salt), form.encode("utf-8"), hashlib.sha256).hexdigest()

# --------------------------------------------------------------------------------------- detectors

# Credential prefixes in the style of gitleaks' rules: each has a fixed vendor prefix, so a match is
# very unlikely to be ordinary text. Conservative by design: an unprefixed high-entropy string is not
# flagged (that is where the false positives are).
CREDENTIAL_PATTERNS = [
    re.compile(r"-----BEGIN [A-Z0-9 ]*PRIVATE KEY(?: BLOCK)?-----[\s\S]*?(?:-----END [A-Z0-9 ]*PRIVATE KEY(?: BLOCK)?-----|\Z)"),
    re.compile(r"\b(?:AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16}\b"),                 # AWS access key id
    re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,255}\b"),                         # GitHub token
    re.compile(r"\bgithub_pat_[A-Za-z0-9_]{50,255}\b"),                       # GitHub fine-grained PAT
    re.compile(r"\bglpat-[A-Za-z0-9_-]{20,}"),                                # GitLab PAT
    re.compile(r"\bxox[abposr]-[A-Za-z0-9-]{10,}"),                           # Slack token
    re.compile(r"https://hooks\.slack\.com/services/[A-Za-z0-9/_-]{20,}"),    # Slack webhook
    re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b"),                                 # Google API key
    re.compile(r"\b[rs]k_live_[0-9A-Za-z]{20,}\b"),                           # Stripe live key
    re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}"),                               # Anthropic API key
    re.compile(r"\bsk-(?:proj|svcacct|admin)-[A-Za-z0-9_-]{20,}"),            # OpenAI API key
    re.compile(r"\bnpm_[A-Za-z0-9]{36}\b"),                                   # npm token
    re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),  # JWT
]

EMAIL = re.compile(r"(?<![A-Za-z0-9._%+-])([A-Za-z0-9._%+-]+)@((?:[A-Za-z0-9-]+\.)+[A-Za-z]{2,})\b")
# Not personal data: an SSH remote's user, and the domains reserved for examples (RFC 2606, RFC 6761).
EMAIL_SKIP_LOCAL = ("git",)
EMAIL_SKIP_DOMAIN = re.compile(r"(?:^|\.)(?:example\.(?:com|org|net)|example|test|invalid|localhost|users\.noreply\.github\.com)$",
                               re.IGNORECASE)

CARD = re.compile(r"(?<![\d-])\d(?:[ -]?\d){14,15}(?![\d-])")
CPF = re.compile(r"(?<![\d.])\d{3}\.\d{3}\.\d{3}-\d{2}(?![\d-])")
CNPJ = re.compile(r"(?<![\d.])\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}(?![\d-])")


def _luhn_ok(digits):
    total = 0
    for i, ch in enumerate(reversed(digits)):
        d = int(ch)
        if i % 2:
            d = d * 2 - 9 if d > 4 else d * 2
        total += d
    return total % 10 == 0


def _card_ok(digits):
    if len(digits) == 15:
        prefix_ok = digits[:2] in ("34", "37")                                # Amex
    else:
        p2, p4 = int(digits[:2]), int(digits[:4])
        prefix_ok = digits[0] == "4" or 51 <= p2 <= 55 or 2221 <= p4 <= 2720 or digits[:4] == "6011" or p2 == 65
    return prefix_ok and _luhn_ok(digits)


def _mod11_digit(digits, weights):
    s = sum(int(d) * w for d, w in zip(digits, weights)) % 11
    return 0 if s < 2 else 11 - s


def cpf_ok(digits):
    if len(digits) != 11 or len(set(digits)) == 1:
        return False
    d1 = _mod11_digit(digits[:9], range(10, 1, -1))
    d2 = _mod11_digit(digits[:9] + str(d1), range(11, 1, -1))
    return digits[9:] == "%d%d" % (d1, d2)


def cnpj_ok(digits):
    if len(digits) != 14 or len(set(digits)) == 1:
        return False
    w1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
    d1 = _mod11_digit(digits[:12], w1)
    d2 = _mod11_digit(digits[:12] + str(d1), [6] + w1)
    return digits[12:] == "%d%d" % (d1, d2)


def find_spans(text, term_hashes=frozenset(), salt=None):
    """[(start, end, category)] for every finding. Categories: employer-client-term, credential,
    email, payment-card, cpf, cnpj. Never returns the matched text itself."""
    spans = []
    for rx in CREDENTIAL_PATTERNS:
        spans += [(m.start(), m.end(), "credential") for m in rx.finditer(text)]
    for m in EMAIL.finditer(text):
        if m.group(1).lower() not in EMAIL_SKIP_LOCAL and not EMAIL_SKIP_DOMAIN.search(m.group(2)):
            spans.append((m.start(), m.end(), "email"))
    for m in CARD.finditer(text):
        if _card_ok(re.sub(r"[ -]", "", m.group(0))):
            spans.append((m.start(), m.end(), "payment-card"))
    spans += [(m.start(), m.end(), "cpf") for m in CPF.finditer(text) if cpf_ok(re.sub(r"\D", "", m.group(0)))]
    spans += [(m.start(), m.end(), "cnpj") for m in CNPJ.finditer(text) if cnpj_ok(re.sub(r"\D", "", m.group(0)))]
    if term_hashes and salt:
        words = tokens(text)
        for i in range(len(words)):
            for n in range(1, min(MAX_TERM_TOKENS, len(words) - i) + 1):
                group = [w[2] for w in words[i:i + n]]
                forms = {" ".join(group), "".join(group)}
                if any(term_hash(salt, f) in term_hashes for f in forms):
                    spans.append((words[i][0], words[i + n - 1][1], "employer-client-term"))
    return spans


def categories(spans):
    order = ["employer-client-term", "credential", "email", "payment-card", "cpf", "cnpj"]
    found = {s[2] for s in spans}
    return [c for c in order if c in found]


def sanitise(text, spans):
    """Replace every finding with [REDACTED:<category>]. Overlapping findings merge into one, labelled
    by the earliest-starting one. The replacement is not reversible: no mapping is kept anywhere."""
    out, pos = [], 0
    merged = []
    for start, end, cat in sorted(spans):
        if merged and start < merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end, cat])
    for start, end, cat in merged:
        out.append(text[pos:start])
        out.append("[REDACTED:%s]" % cat)
        pos = end
    out.append(text[pos:])
    return "".join(out)

# -------------------------------------------------------------------------------------- salt store


class SaltStore:
    """The salt keys every term hash. macOS: the login Keychain (generic password), written through
    `security -i` on stdin so the value never appears in a process's argv. Elsewhere, or by choice: a
    user-only file (0600) in the local overlay directory, outside every repository."""

    def __init__(self, conf, run=subprocess.run):
        self.conf = conf
        self.run = run

    def get(self):
        if self.conf["salt_store"] == "keychain":
            r = self.run(["/usr/bin/security", "find-generic-password", "-s", self.conf["keychain_service"],
                          "-a", _account(), "-w"], capture_output=True)
            value = r.stdout.decode().strip() if r.returncode == 0 else ""
        else:
            try:
                with open(self.conf["salt_file"], encoding="ascii") as fh:
                    value = fh.read().strip()
            except OSError:
                value = ""
        return value if re.fullmatch(r"[0-9a-f]{64}", value) else None

    def create(self):
        value = secrets.token_hex(32)
        if self.conf["salt_store"] == "keychain":
            cmd = 'add-generic-password -s "%s" -a "%s" -w "%s"\n' % (self.conf["keychain_service"], _account(), value)
            r = self.run(["/usr/bin/security", "-i"], input=cmd.encode(), capture_output=True)
            if r.returncode != 0:
                raise RuntimeError("could not store the salt in the Keychain")
        else:
            _private_dir(os.path.dirname(self.conf["salt_file"]))
            _atomic_write(self.conf["salt_file"], value + "\n")
        if self.get() != value:
            raise RuntimeError("the salt was written but does not read back")
        return value

    def get_or_create(self):
        return self.get() or self.create()


def _account():
    return os.environ.get("USER") or str(os.getuid())


def _private_dir(path):
    os.makedirs(path, mode=0o700, exist_ok=True)
    os.chmod(path, 0o700)


def _atomic_write(path, content):
    tmp = "%s.new.%d" % (path, os.getpid())
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="ascii") as fh:
        fh.write(content)
    os.replace(tmp, path)

# -------------------------------------------------------------------------------------- term list


def read_terms(path):
    try:
        with open(path, encoding="ascii") as fh:
            return frozenset(line.strip() for line in fh if re.fullmatch(r"[0-9a-f]{64}", line.strip()))
    except OSError:
        return frozenset()


def add_term_hashes(path, hashes):
    _private_dir(os.path.dirname(path))
    current = read_terms(path)
    new = [h for h in hashes if h not in current]
    lines = sorted(current | set(new))
    _atomic_write(path, TERMS_HEADER + "".join(h + "\n" for h in lines))
    return len(new)

# ------------------------------------------------------------------------------------- notifier


# Fixed scripts: every variable part arrives as an argv item, so nothing is ever spliced into code.
NOTIFY_SCRIPT = [
    "on run argv",
    "display notification (item 1 of argv) with title (item 2 of argv)",
    "end run",
]
OFFER_SCRIPT = [
    "on run argv",
    "set r to display dialog (item 1 of argv) with title (item 2 of argv) "
    "buttons {item 4 of argv, item 5 of argv, item 6 of argv} default button (item 4 of argv) "
    "giving up after (item 3 of argv as integer)",
    "return button returned of r",
    "end run",
]


class Notifier:
    """Notices through osascript. The text is a fixed template plus category names: the copied content
    is never an argument, so it cannot reach argv, a notification or Notification Center's history."""

    def __init__(self, conf, run=subprocess.run):
        self.conf = conf
        self.run = run

    def _osascript(self, lines, args):
        cmd = [self.conf["osascript"]]
        for line in lines:
            cmd += ["-e", line]
        return self.run(cmd + list(args), capture_output=True, timeout=int(self.conf["dialog_seconds"]) + 30)

    def notify(self, key, **values):
        """Never raises: a notifier that crashes the watcher would turn one failed notice into no watch."""
        try:
            text = self.conf[key].format(**values)
        except (KeyError, IndexError, ValueError):
            text = DEFAULTS[key].format(**values)   # an overlay template with a bad placeholder
        try:
            r = self._osascript(NOTIFY_SCRIPT, [text, self.conf["title"]])
            return r.returncode == 0
        except (OSError, subprocess.SubprocessError):
            return False

    def offer(self, cats):
        """Ask clean / clear / keep. Anything but an explicit Clean or Clear (timeout, dismissal, an
        osascript failure) is Keep: the clipboard is left exactly as copied."""
        try:
            text = self.conf["notice_offer"].format(categories=", ".join(cats))
        except (KeyError, IndexError, ValueError):
            text = DEFAULTS["notice_offer"].format(categories=", ".join(cats))
        keep, clear, clean = self.conf["button_keep"], self.conf["button_clear"], self.conf["button_clean"]
        try:
            r = self._osascript(OFFER_SCRIPT, [text, self.conf["title"], self.conf["dialog_seconds"], keep, clear, clean])
        except (OSError, subprocess.SubprocessError):
            return "keep"
        answer = r.stdout.decode("utf-8", "replace").strip() if r.returncode == 0 else ""
        if len({keep, clear, clean}) < 3:      # ambiguous labels: never guess which act was meant
            return "keep"
        return {clean: "clean", clear: "clear"}.get(answer, "keep")

# ---------------------------------------------------------------------------------- pasteboard


class MacPasteboard:
    """NSPasteboard through the Objective-C runtime with ctypes (no third-party module). `name` selects
    a private named pasteboard (tests); None is the general pasteboard (the watcher)."""

    def __init__(self, name=None):
        import ctypes
        self.c = ctypes
        self.objc = ctypes.cdll.LoadLibrary("/usr/lib/libobjc.A.dylib")
        ctypes.cdll.LoadLibrary("/System/Library/Frameworks/AppKit.framework/AppKit")
        self.objc.objc_getClass.restype = ctypes.c_void_p
        self.objc.objc_getClass.argtypes = [ctypes.c_char_p]
        self.objc.sel_registerName.restype = ctypes.c_void_p
        self.objc.sel_registerName.argtypes = [ctypes.c_char_p]
        with self._pool():
            cls = self._cls("NSPasteboard")
            if name is None:
                pb = self._send(ctypes.c_void_p, cls, "generalPasteboard")
            else:
                pb = self._send(ctypes.c_void_p, cls, "pasteboardWithName:", (ctypes.c_void_p, self._ns(name)))
            self.pb = self._send(ctypes.c_void_p, pb, "retain")

    def _cls(self, name):
        return self.objc.objc_getClass(name.encode())

    def _send(self, restype, obj, sel, *args):
        c = self.c
        fn = c.CFUNCTYPE(restype, c.c_void_p, c.c_void_p, *[a[0] for a in args])(("objc_msgSend", self.objc))
        return fn(obj, self.objc.sel_registerName(sel.encode()), *[a[1] for a in args])

    def _ns(self, s):
        return self._send(self.c.c_void_p, self._cls("NSString"), "stringWithUTF8String:",
                          (self.c.c_char_p, s.encode("utf-8")))

    def _py(self, ns):
        if not ns:
            return None
        return self.c.string_at(self._send(self.c.c_void_p, ns, "UTF8String")).decode("utf-8", "replace")

    def _pool(self):
        outer = self

        class Pool:
            def __enter__(self):
                c = outer.c
                self.p = outer._send(c.c_void_p, outer._send(c.c_void_p, outer._cls("NSAutoreleasePool"), "alloc"), "init")

            def __exit__(self, *exc):
                outer._send(None, self.p, "drain")
        return Pool()

    def change_count(self):
        with self._pool():
            return self._send(self.c.c_long, self.pb, "changeCount")

    def types(self):
        c = self.c
        with self._pool():
            arr = self._send(c.c_void_p, self.pb, "types")
            if not arr:
                return []
            n = self._send(c.c_ulong, arr, "count")
            return [self._py(self._send(c.c_void_p, arr, "objectAtIndex:", (c.c_ulong, i))) for i in range(n)]

    def string(self):
        with self._pool():
            return self._py(self._send(self.c.c_void_p, self.pb, "stringForType:", (self.c.c_void_p, self._ns(TEXT_TYPE))))

    def put(self, items):
        """Replace the whole item (every flavour) with {type: string}."""
        c = self.c
        with self._pool():
            self._send(c.c_long, self.pb, "clearContents")
            for t, s in items.items():
                self._send(c.c_bool, self.pb, "setString:forType:", (c.c_void_p, self._ns(s)), (c.c_void_p, self._ns(t)))

    def set_string(self, s):
        self.put({TEXT_TYPE: s})

    def clear(self):
        with self._pool():
            self._send(self.c.c_long, self.pb, "clearContents")

    def release(self):
        """Destroy a private named pasteboard (tests)."""
        with self._pool():
            self._send(None, self.pb, "releaseGlobally")

# ----------------------------------------------------------------------------------- the watcher


def is_marked(type_name):
    """True for a password-manager marker: the nspasteboard.org UTIs, or a type name carrying one."""
    low = (type_name or "").lower()
    return type_name in SKIP_TYPES or any(s in low for s in SKIP_SUBSTRINGS)


class Guard:
    def __init__(self, conf, pasteboard, notifier, salts):
        self.conf = conf
        self.pb = pasteboard
        self.notifier = notifier
        self.salts = salts
        self.salt = None
        self.terms = frozenset()
        self.terms_stamp = None
        self.warned_no_salt = False

    def refresh_terms(self):
        """Re-read the term list when it changes, so a term added while the watcher runs counts at once."""
        try:
            st = os.stat(self.conf["terms_file"])
            stamp = (st.st_mtime_ns, st.st_size)
        except OSError:
            stamp = None
        if stamp == self.terms_stamp:
            return
        self.terms_stamp = stamp
        self.terms = read_terms(self.conf["terms_file"])
        if self.terms and not self.salt:
            self.salt = self.salts.get()
            if not self.salt and not self.warned_no_salt:
                self.warned_no_salt = True
                self.notifier.notify("notice_no_salt")

    def check(self, change_count):
        """Check the item at change_count once. Returns what happened, for tests; keeps nothing."""
        if any(is_marked(t) for t in self.pb.types()):
            return "skipped-marked"
        text = self.pb.string()
        if text is None:
            return "no-text"
        if len(text.encode("utf-8")) > int(self.conf["max_bytes"]):
            self.notifier.notify("notice_too_large", max=self.conf["max_bytes"])
            return "too-large"
        self.refresh_terms()
        spans = find_spans(text, self.terms, self.salt)
        if not spans:
            return "clean"
        cats = ", ".join(categories(spans))
        choice = "clean" if self.conf["mode"] == "sanitise" else self.notifier.offer(categories(spans))
        if choice == "keep":
            return "kept"
        if self.pb.change_count() != change_count:
            self.notifier.notify("notice_changed", categories=cats)
            return "changed"
        if choice == "clear":
            self.pb.clear()
            self.notifier.notify("notice_cleared", categories=cats)
            return "cleared"
        self.pb.set_string(sanitise(text, spans))
        self.notifier.notify("notice_cleaned", categories=cats)
        return "cleaned"

    def run(self, max_cycles=None):
        last = None
        cycles = 0
        while max_cycles is None or cycles < max_cycles:
            cycles += 1
            try:
                cc = self.pb.change_count()
                if cc != last:
                    self.check(cc)
                    last = self.pb.change_count()
            except Exception as exc:  # a crash would end the watch silently; report the class only,
                # because an exception's message can quote the input. Mark the item seen so one bad
                # item yields one notice, not one per poll.
                last = self._safe_count(last)
                self.notifier.notify("notice_error", error=type(exc).__name__)
            time.sleep(int(self.conf["poll_seconds"]))

    def _safe_count(self, fallback):
        try:
            return self.pb.change_count()
        except Exception:
            return fallback

# ------------------------------------------------------------------------------------------ CLI

USAGE = """usage:
  clipboard_guard.py watch [--config FILE]         the background watcher (run by the LaunchAgent)
  clipboard_guard.py add-term [--config FILE]      add one term, typed at your terminal with echo off
  clipboard_guard.py check-config [--config FILE]  print the effective non-secret settings
No command takes a term as an argument.
"""

AGENT_MARKERS = ("CLAUDECODE", "CLAUDE_CODE_ENTRYPOINT", "AI_AGENT", "CODEX_SANDBOX",
                 "CODEX_SANDBOX_NETWORK_DISABLED")


def _read_secret_line(tty_fd, prompt):
    import termios
    old = termios.tcgetattr(tty_fd)
    new = termios.tcgetattr(tty_fd)
    new[3] &= ~termios.ECHO
    try:
        # Echo goes off BEFORE the prompt appears, so nothing typed after the prompt is ever echoed.
        termios.tcsetattr(tty_fd, termios.TCSADRAIN, new)
        os.write(tty_fd, prompt.encode())
        buf = b""
        while not buf.endswith(b"\n"):
            chunk = os.read(tty_fd, 1024)
            if not chunk:
                break
            buf += chunk
    finally:
        termios.tcsetattr(tty_fd, termios.TCSADRAIN, old)
        os.write(tty_fd, b"\n")
    return buf.decode("utf-8", "replace").rstrip("\r\n")


def cmd_add_term(conf, out=sys.stdout):
    present = [m for m in AGENT_MARKERS if os.environ.get(m)]
    if present:
        out.write("refused: an agent session marker is set (%s). Add terms from your own terminal, outside "
                  "any agent session, so the term never enters a transcript.\n" % ", ".join(present))
        return 2
    if not os.isatty(0):
        out.write("refused: stdin is not a terminal. The term is read only from the terminal, with echo off.\n")
        return 2
    try:
        tty = os.open("/dev/tty", os.O_RDWR | os.O_NOCTTY)
    except OSError:
        out.write("refused: no controlling terminal.\n")
        return 2
    try:
        first = _read_secret_line(tty, "Term (not shown): ")
        second = _read_secret_line(tty, "Again: ")
    finally:
        os.close(tty)
    if first != second:
        out.write("not added: the two entries differ.\n")
        return 1
    forms = term_forms(first)
    del first, second
    if not forms or len(forms[0].split(" ")) > MAX_TERM_TOKENS or len(forms[0].replace(" ", "")) < MIN_TERM_CHARS:
        out.write("not added: a term has 1 to %d words and at least %d letters or digits.\n" % (MAX_TERM_TOKENS, MIN_TERM_CHARS))
        return 1
    salt = SaltStore(conf).get_or_create()
    n = add_term_hashes(conf["terms_file"], [term_hash(salt, f) for f in forms])
    del forms
    out.write("added: %d new hash(es) to %s. The term itself was not stored anywhere.\n" % (n, conf["terms_file"]))
    return 0


def main(argv):
    args = list(argv[1:])
    if not args or args[0] in ("-h", "--help"):
        sys.stdout.write(USAGE)
        return 0
    command, rest = args[0], args[1:]
    config, pasteboard, max_cycles = None, None, None
    while rest:
        flag = rest.pop(0)
        if flag == "--config" and rest:
            config = rest.pop(0)
        elif flag == "--pasteboard" and rest:      # a private named pasteboard, for tests
            pasteboard = rest.pop(0)
        elif flag == "--max-cycles" and rest and rest[0].isdigit():  # for tests
            max_cycles = int(rest.pop(0))
        else:
            sys.stderr.write("unknown or incomplete argument: %s (no term is ever taken from arguments)\n" % flag)
            return 2
    conf = load_config(config)
    if command == "add-term":
        return cmd_add_term(conf)
    if command == "check-config":
        for key in ("mode", "poll_seconds", "max_bytes", "salt_store", "keychain_service", "terms_file", "salt_file"):
            sys.stdout.write("%s=%s\n" % (key, conf[key]))
        sys.stdout.write("terms=%d\n" % len(read_terms(conf["terms_file"])))
        return 0
    if command == "watch":
        if sys.platform != "darwin":
            sys.stderr.write("watch: only macOS has a backend (see ADR-0011 for Linux and Windows)\n")
            return 2
        Guard(conf, MacPasteboard(pasteboard), Notifier(conf), SaltStore(conf)).run(max_cycles)
        return 0
    sys.stderr.write("unknown command: %s\n" % command)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
